### ISSUE TITLE
通知員工、主管的方法

### ISSUE THREAD

**Issue by Tobydog0501** [DavidWu94/server#1]
我目前有兩個選項：
- 使用docker建置ntfy
- 使用nodemailer寄送郵件
以下是兩個選項的優缺點
---
# 選項一
優點：
- 沒有限制

缺點：
- 建設在windows較為困難
- 會涉及隱私問題，需要以編號的方式來通知
---
# 選項二
優點：
- 建置上較為容易
- 沒有隱私問題

缺點：
- google有限制一天最多500封信件
---
以上我認為選項二較為可行
但決定在你

**Comment by DavidWu94** [comment]
嘗試看看用docker建置ntfy好了

Tobydog0501 ***@***.***>於 2024年1月17日 週三，下午12:57寫道：

**Comment by Tobydog0501** [comment]
如果電腦系統是Linux會好建置一點🤣
